// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD40h-R0Xvq61up_TepYc53nTV4_V0CHnI',
    appId: '1:3361174751:web:fa3446b279b4714d3e256a',
    messagingSenderId: '3361174751',
    projectId: 'forecastproject-9c7e1',
    authDomain: 'forecastproject-9c7e1.firebaseapp.com',
    storageBucket: 'forecastproject-9c7e1.appspot.com',
    measurementId: 'G-8814CEKLL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuPTKx8MnUjE3yD9zgWwL5QhXWtbYi2k',
    appId: '1:3361174751:android:719ea263203417853e256a',
    messagingSenderId: '3361174751',
    projectId: 'forecastproject-9c7e1',
    storageBucket: 'forecastproject-9c7e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8izrJbZ9RgFtvL9pv5XSOl7mskEMzE-s',
    appId: '1:3361174751:ios:4ec546cad56e73953e256a',
    messagingSenderId: '3361174751',
    projectId: 'forecastproject-9c7e1',
    storageBucket: 'forecastproject-9c7e1.appspot.com',
    iosClientId: '3361174751-15aetr6bsje26lb7685fecv4b9pnv20o.apps.googleusercontent.com',
    iosBundleId: 'com.example.forecast',
  );
}
